server:
  port: 8188
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.25.134:3306/personal?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: shanejim
    password: Shanejim123,,,s



