server:
  port: 8188
spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://192.168.180.128:33714/personal?characterEncoding=utf-8
    username: shanejim
    password: Shanejim123,,,
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false #开发阶段，建议关闭Thymeleaf的缓存
    mode: LEGACYHTML5 #使用遗留的html5以去掉对html标签的校验
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.shanejim.myweb.personalmodel.entity

jedis:
    host: "192.168.180.128"
    database: 8
    password: xiaojian123,,,
    port: 65156
    maxTotal: 1000
    maxIdle: 50
    maxWaitMillis: 1500
    testOnBorrow: true
    testOnReturn: true

system-params:
  image-hosturl: http://img.xsmore.com/wxrobot

#静态资源对外暴露的访问路径
file:
  staticAccessPath: /file/**
  uploadFolder: /var/spring/uploadFiles/
#文件上传目录（注意Linux和Windows上的目录结构不同，开发机Windows，application-dev里面）

