server:
  port: 8188
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.180.128:33714/personal?characterEncoding=utf-8
    username: shanejim
    password: Shanejim123,,,
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false #开发阶段，建议关闭Thymeleaf的缓存
    mode: LEGACYHTML5 #使用遗留的html5以去掉对html标签的校验
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.shanejim.myweb.personalmodel.entity


system-params:
  image-hosturl: http://img.xsmore.com/wxrobot

